
# PyTorch Practice Notebook (Beginner → Advanced)

This notebook is a **hands-on, from-scratch PyTorch guide**.
Each section explains **syntax + concepts + examples**.

Topics covered:
1. Tensors & Basics
2. Autograd
3. Neural Networks
4. Training Loop
5. GPU usage
6. Custom Datasets & DataLoader
7. CNNs
8. Transfer Learning
9. Saving & Loading Models


In [1]:

import torch
import torch.nn as nn
import torch.optim as optim
print("PyTorch version:", torch.__version__)


PyTorch version: 2.6.0+cu118



## 1. Tensors (Core Data Structure)

`torch.Tensor` is similar to NumPy arrays but supports **GPU acceleration** and **automatic differentiation**.


In [2]:

# Creating tensors
a = torch.tensor([1, 2, 3])
b = torch.zeros((2, 3))
c = torch.ones((3, 3))
d = torch.rand((2, 2))

print(a)
print(b)
print(c)
print(d)


tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4426, 0.7070],
        [0.4333, 0.1035]])



### Tensor Operations


In [3]:

x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(x + y)        # Element-wise addition
print(x * y)        # Element-wise multiplication
print(torch.dot(x, y))  # Dot product


tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)



## 2. Autograd (Automatic Differentiation)

PyTorch automatically computes gradients if `requires_grad=True`.


In [4]:

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3*x + 1
y.backward()

print("dy/dx:", x.grad)


dy/dx: tensor(7.)



## 3. Neural Networks with `nn.Module`


In [5]:

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(1, 10)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(10, 1)

    def forward(self, x):
        x = self.linear1(x)
        x = self.relu(x)
        return self.linear2(x)

model = SimpleNN()
print(model)


SimpleNN(
  (linear1): Linear(in_features=1, out_features=10, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=10, out_features=1, bias=True)
)



## 4. Training Loop (Core PyTorch Skill)


In [6]:

# Dummy data
X = torch.randn(100, 1)
y = 3*X + 2

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):
    optimizer.zero_grad()
    preds = model(X)
    loss = criterion(preds, y)
    loss.backward()
    optimizer.step()

print("Final loss:", loss.item())


Final loss: 0.15994597971439362



## 5. GPU Usage


In [7]:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print("Using device:", device)


Using device: cpu



## 6. Custom Dataset & DataLoader


In [8]:

from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self):
        self.x = torch.randn(100, 1)
        self.y = 2*self.x + 1

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

dataset = MyDataset()
loader = DataLoader(dataset, batch_size=16, shuffle=True)

for batch_x, batch_y in loader:
    print(batch_x.shape)
    break


torch.Size([16, 1])



## 7. CNN Example (Image Data)


In [9]:

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(1, 16, 3)
        self.fc = nn.Linear(16*26*26, 10)

    def forward(self, x):
        x = self.conv(x)
        x = torch.relu(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

cnn = SimpleCNN()
print(cnn)


SimpleCNN(
  (conv): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc): Linear(in_features=10816, out_features=10, bias=True)
)



## 8. Saving & Loading Models


In [10]:

torch.save(model.state_dict(), "model.pth")

loaded_model = SimpleNN()
loaded_model.load_state_dict(torch.load("model.pth"))
loaded_model.eval()


SimpleNN(
  (linear1): Linear(in_features=1, out_features=10, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=10, out_features=1, bias=True)
)